# Computação Numérica com Numpy
<br>
<br>

In [1]:
import numpy as np

## Criando arrays

In [2]:
# Criando um array unidimensional
array1 = np.array([10, 20, 30, 40])

In [3]:
# Criando um array bi-dimensional
array2 = np.array([[100, 83, 15], [42, 78, 0]])

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

## Verificando o formato do array

In [6]:
array1.shape

(4,)

In [7]:
array2.shape

(2, 3)

## Verificando o numero de dimensoes

In [8]:
array2.ndim

2

## Acessando métodos

In [9]:
array2.max()

100

## Acessando atributos

In [10]:
array2.ndim

2

## Criando estruturas de dados com arange

In [11]:
array3 = np.arange(15)

In [12]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
array4 = np.arange(0, 15, 5)

In [14]:
array4

array([ 0,  5, 10])

## Criando estruturas de dados com linspace

In [15]:
array5 = np.linspace(9, 3, 4)
array5

array([9., 7., 5., 3.])

## Criando estruturas de dados com outras funções

In [16]:
# Array com zeros
array6 = np.zeros((10,8))
array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# Array com um's
array7 = np.ones((2, 3, 2))
array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
# Produz um identity matrix
array8 = np.eye(3)
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Matriz diagonal
array9 = np.diag((2, 1, 4, 6))
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [20]:
# Valores randomicos
np.random.seed(100)
array10 = np.random.rand(5)
array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [21]:
# Produz uma sequencia de numeros com distribuicao normal (Gaussian)
array11 = np.random.randn(5)
array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [22]:
# Produz um array vazio
array12 = np.empty((3, 2))
array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
# Duplica o array em colunas
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [24]:
# Duplica o array em linhas e colunas
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de dados numpy

In [25]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')
array13

array([ 8., -3.,  5.,  9.])

In [26]:
array13.dtype

dtype('float64')

In [27]:
array14 = np.array([2, 4, 6, 8])
array14

array([2, 4, 6, 8])

In [28]:
array14.dtype

dtype('int32')

In [29]:
array15 = np.array([2.0, 4, 6, 8])
array15

array([2., 4., 6., 8.])

In [30]:
array15.dtype

dtype('float64')

In [31]:
array16 = np.array(['Análise', 'de', 'Dados', 'com Python'])
array16

array(['Análise', 'de', 'Dados', 'com Python'], dtype='<U10')

In [32]:
array16.dtype

dtype('<U10')

In [33]:
array17 = np.array([True, False, True])
array17

array([ True, False,  True])

In [34]:
array17.dtype

dtype('bool')

In [35]:
array18 = np.array([7, -3, 5.24])
array18

array([ 7.  , -3.  ,  5.24])

In [36]:
array18.dtype

dtype('float64')

In [37]:
array18.astype(int)

array([ 7, -3,  5])

## Operações com Arrays

In [38]:
# Criando o array e multiplicando por 5
array19 = np.arange(0,30) * 5
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [39]:
# Criando o array e elevando a potencia
array20 = np.arange(5) ** 4
array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [40]:
# Somando um valor
array21 = np.arange(0, 30) + 1
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
array22 = np.arange(0, 30, 3) + 3
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [42]:
array23 = np.arange(1, 11)
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [45]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [46]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [47]:
# Podemos comparar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [48]:
array24 = np.array([True, False, True, False])
array25 = np.array([False, False, True, False])
np.logical_and(array24, array25)

array([False, False,  True, False])

## Comparando o tempo entre array com numpy e python puro

In [49]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

3.67 µs ± 58.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

405 µs ± 9.65 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
