# Operações Matemáticas - Arrays e Matrizes
<br><br>

## NumPy

### Arrays NumPy - objetos multidimensionais com N dimensões.
### Matrizes NumPy - objetos com 2 dimensões. 

A principal vantagem de utilizar matrizes com NumPy, é que este tipo de objeto possui convenientes notações para multiplicação de matrizes. Arrays e Matrizes NumPy possuem o atributo .T para retornar a transposta da matriz, enquanto objetos do tipo matriz possuem adicionalmente os atributos .I (Inversa) e .H (Transposta Conjugada).

Existem diferenças em operações de álgebra linear entre arrays e matrizes.

Muitas funções NumPy retornam arrays e não matrizes como objeto resultante.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]


'1.20.1'

## Criando Matrizes

In [2]:
mat1 = np.matrix("1,2,3; 4,5,6")
print(mat1)

[[1 2 3]
 [4 5 6]]


In [3]:
type(mat1)

numpy.matrix

In [4]:
mat2 = np.matrix( [ [1,2,3], [4,5,6] ] )
print(mat2)

[[1 2 3]
 [4 5 6]]


In [5]:
mat3 = np.matrix([ [0,10,0,0,0], [0,0,20,0,0], [0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0] ]) 
print(mat3)

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]


In [6]:
type(mat3)

numpy.matrix

In [7]:
mat3[2, 3]

30

## Operações Matemáticas com Arrays e Matrizes

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
type(a)

numpy.ndarray

In [10]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [11]:
A = np.mat(a)
A

matrix([[1, 2],
        [3, 4]])

In [12]:
type(A)

numpy.matrix

In [13]:
A * A

matrix([[ 7, 10],
        [15, 22]])

## $$  \boxed{ \begin{align} \begin{pmatrix} 1 & 2    \\ 3 &  4   \end{pmatrix} & \begin{pmatrix} 1 & 2    \\ 3 &  4   \end{pmatrix}  = \begin{pmatrix} 7 & 10    \\ 15 &  22   \end{pmatrix} \end{align} }$$

In [ ]:
from IPython.display import Image
Image('imagens/Matriz.png')

In [ ]:
np.dot(a, a) 

In [ ]:
# Convertendo um Array para Matriz
mat5 = np.asmatrix(a)

In [ ]:
mat5

In [ ]:
mat5 * mat5

In [ ]:
# Convertendo uma Matriz para Array
array2 = np.asarray(mat5)

In [ ]:
array2

In [ ]:
array2 * array2

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>